// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NewServer_V2.Models;

namespace NewServer_V2.Migrations
{
    [DbContext(typeof(ParkingDbContext))]
    [Migration("20190504003009_Update")]
    partial class Update
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062");

            modelBuilder.Entity("NewServer_V2.Models.Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Input");

                    b.Property<string>("LicensePlate");

                    b.Property<DateTime>("Output");

                    b.Property<string>("Owner");

                    b.Property<int?>("PlaceId");

                    b.HasKey("Id");

                    b.HasIndex("PlaceId");

                    b.ToTable("Cars");
                });

            modelBuilder.Entity("NewServer_V2.Models.Floor", b =>
                {
                    b.Property<int>("FloorId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("NFloor");

                    b.HasKey("FloorId");

                    b.ToTable("Floors");
                });

            modelBuilder.Entity("NewServer_V2.Models.Place", b =>
                {
                    b.Property<int>("PlaceId")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("FloorId");

                    b.Property<bool>("State");

                    b.HasKey("PlaceId");

                    b.HasIndex("FloorId");

                    b.ToTable("Places");
                });

            modelBuilder.Entity("NewServer_V2.Models.Car", b =>
                {
                    b.HasOne("NewServer_V2.Models.Place", "Place")
                        .WithMany("Records")
                        .HasForeignKey("PlaceId");
                });

            modelBuilder.Entity("NewServer_V2.Models.Place", b =>
                {
                    b.HasOne("NewServer_V2.Models.Floor", "Floor")
                        .WithMany("Places")
                        .HasForeignKey("FloorId");
                });
#pragma warning restore 612, 618
        }
    }
}
